#!/bin/sh

cat <<EOF > /usr/share/nginx/html/config.json
{
  "REACT_APP_VAPORCORE_URL": "${REACT_APP_VAPORCORE_URL}",
  "REACT_APP_AWS_S3_BUCKET": "${REACT_APP_AWS_S3_BUCKET}",
  "REACT_APP_AWS_S3_BUCKET_USER_KEY": "${REACT_APP_AWS_S3_BUCKET_USER_KEY}",
  "REACT_APP_AWS_S3_BUCKET_USER_SECRET": "${REACT_APP_AWS_S3_BUCKET_USER_SECRET}",
  "REACT_APP_AWS_S3_KMS_KEY_ID": "${REACT_APP_AWS_S3_KMS_KEY_ID}",
  "REACT_APP_AWS_REGION": "${REACT_APP_AWS_REGION}",
  "REACT_APP_VAPORFLOW_URL": "${REACT_APP_VAPORFLOW_URL}",
}
EOF
